function worldmap_res(catalogName)
tempCatFN= 'temp_earthquake_cat_merge.mat';
minMag = 6.5;
delete_temp         = @() system(sprintf('rm %s',tempCatFN));

worldmap_base()

load('IRIS_DMC_with_FMS.mat'); %#ok<LOAD>
h = scatterm(CAT.lat,CAT.lon,2,[0 0 0], 'filled');
h.Children.MarkerFaceAlpha = .1;

switch catalogName
    case 'ISC'
        aftershock_productivity_kernel( quakes.otime, ...
            quakes.lat, ...
            quakes.lon, ...
            quakes.depth, ...
            quakes.mag, ...
            'SaveCatalog',tempCatFN, ...
            'MinMainshockMag',minMag, ...
            'DepthRange',[0,55], ...
            'PlotYN', 'no');
        CAT = load(tempCatFN); delete_temp();
        scatterm(CAT.MSlat, CAT.MSlon, ...
            (CAT.MSmag-3).^3, CAT.MSres, ...
            'filled','MarkerFaceAlpha',0.2)
    case 'gCMT'
        shapes = {'^','s','o'};
        aftershock_productivity_kernel(...
        	'eq_catalog.mat', ...
            'DepthRange',[0,55], ...
            'SaveCatalog',tempCatFN, ...
            'MinMainshockMag',minMag, ...
            'PlotYN', 'no');
        CAT = load(tempCatFN); delete_temp();
        hAry   = cell(3,1);
        for n = 1:3
            I = CAT.MSfms == n;
            hAry{n} = scatterm(CAT.MSlat(I), CAT.MSlon(I), ...
                (CAT.MSmag(I)-2).^3, CAT.MSres(I), ...
                shapes{n}, ...
                'filled','MarkerFaceAlpha',0.2);
            hAry{n}.Children.MarkerFaceAlpha = .7;

        end
        legend([hAry{:}],{'Strike-Slip','Normal','Reverse'});
        
    case 'gCMT-ISC'
        shapes = {'^','s','o'};
        CAT = aftershock_productivity_GCMT_ISC();
        for n = 1:3
            I = CAT.MSfms == n;
            hAry{n} = scatterm(CAT.MSlat(I), CAT.MSlon(I), ...
                (CAT.MSmag_appended_cat1(I)-2).^3, CAT.MSres_appended_cat1(I), ...
                shapes{n}, ...
                'filled','MarkerFaceAlpha',0.2);
        end
        legend([hAry{:}],{'Strike-Slip','Normal','Reverse'});
    case 'Plate boundaries'
        CAT = plate_boundaries('no');
        
        shapes = {'o','s','d','^','p','h','v','>'};
        fnames = fieldnames(CAT);
        nNames = length(fnames);
        hAry   = cell(nNames,1);
        for n= 1:nNames
            c = CAT.(fnames{n});
            I = c.MSmag > 6;
            hAry{n} = scatterm(c.MSlat(I),c.MSlon(I), ...
                (c.MSmag(I)-4).^3,c.MSres_appended_cat1(I), ...
                shapes{n},'filled','MarkerFaceAlpha',0.5);
        end
        legend([hAry{:}],fieldnames(CAT))
    case 'IRIS DMC'
         aftershock_productivity_kernel(...
            CAT.time, ...
            CAT.lat, ...
            CAT.lon, ...
            CAT.depth, ...
            CAT.M, ...
            CAT.fms, ...
            'SaveCatalog',tempCatFN, ...
            'MinMainshockMag',minMag, ...
            'DepthRange',[0,55], ...
            'Completeness', 4.3, ...
            'PlotYN', 'no'); %#ok<NODEF>
        clear CAT
        CAT = load(tempCatFN); delete_temp();
        SM = scatterm(CAT.MSlat, CAT.MSlon, ...
            [], CAT.MSres, ...
            'filled','MarkerFaceAlpha',0.2);
        SM.Children.MarkerFaceAlpha = .8;
        
end
        
end